version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: wicum_mysql_host
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wicum_development
      MYSQL_USER: ecotiya
      MYSQL_PASSWORD: ecotiya
      TZ: Asia/Tokyo
    ports:
      - "3306:3306"
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - mysql-data:/var/lib/mysq

  nginx:
    container_name: wicum_nginx_container
    build:
      context: ./nginx
      dockerfile: ../.docker/nginx/Dockerfile
    restart: on-failure
    volumes:
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
    ports:
      - "80:80"
    depends_on:
      - backend

  frontend:
    container_name: wicum_frontend_container
    build:
      context: ./frontend
      dockerfile: ../.docker/frontend/Dockerfile
    command: sh -c 'yarn start'
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "5000:3000"
    tty: true
    depends_on:
      - backend

  backend:
    container_name: wicum_backend_container
    build:
      context: ./backend
      dockerfile: ../.docker/backend/Dockerfile
    command: /bin/sh -c "rm -f /myapp/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    tty: true
    stdin_open: true
    volumes:
      - ./backend:/myapp
      - public-data:/myapp/public
      - tmp-data:/myapp/tmp
      - log-data:/myapp/log
    environment:
      TZ: Asia/Tokyo
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db

volumes:
  mysql-data:
    driver: local
  public-data:
  tmp-data:
  log-data:
